/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface ContactSubmissions {
  createdAt: Generated<Timestamp>;
  email: string;
  id: Generated<number>;
  language: Generated<string>;
  message: string;
  name: string;
}

export interface DriverRegistrations {
  city: string;
  createdAt: Generated<Timestamp | null>;
  email: string;
  experience: string;
  fullName: string;
  id: Generated<string>;
  language: string;
  message: string | null;
  phone: string;
  vehicleType: string;
}

export interface NewsletterSubscriptions {
  createdAt: Generated<Timestamp>;
  email: string;
  id: Generated<number>;
  language: Generated<string>;
}

export interface PartnershipInquiries {
  companyName: string | null;
  createdAt: Generated<Timestamp>;
  email: string;
  id: Generated<number>;
  language: Generated<string>;
  message: string;
  name: string;
  phone: string | null;
}

export interface DB {
  contactSubmissions: ContactSubmissions;
  driverRegistrations: DriverRegistrations;
  newsletterSubscriptions: NewsletterSubscriptions;
  partnershipInquiries: PartnershipInquiries;
}




// Note: kysely maps the table/column/enum names from snake_case to camelCase and PascalCase. When running SQL statements, make sure to use snake_case, but TypeScript code should use camelCase or PascalCase.